theme: minima
title: My Trial Website
author: GitHub User
email: hemang.cs19@bmsce.ac.in
description: > # this means to ignore newlines until "baseurl:"
  So this is my trial website.This wont give you any information but yaa 
  its just for my practice and learning how to use GitHub  
# social links
twitter_username: Hemang_singh14
github_username:  Hemang14

show_excerpts: true # set to false to remove excerpts on the homepage
